# Site
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Akhil Kasturi
title: PhD Candidate at University of Rochester, NY
email: akasturi@ur.rochester.edu

# Dark Mode (true/false/never)
darkmode: false

# Social links
#github_username:  akhilvrk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: akhil-k-21069711b
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Akhil, an Artificial Intelligence researcher. My expertise spans across Deep Learning, Machine Learning, and Statistical Models, with a strong focus on Digital Image, Signal and Audio Processing and Data Analysis as well as AR/VR technologies. My current role involves research in Computer Vision and Natural Language Processing (NLP) for Computer Aided Diagnostic applications.
  
  I am skilled  in: <mark>Deep Learning</mark>,  <mark>Computer Vision</mark>, <mark>Signal Processing</mark> and "


# Education Section
education:
  - title: Education
    layout: list
    content:
      - layout: left
        title: University of Rochester
        caption: August 2022 - August 2024
        sub_title: PhD, Computer Engineering
        description: |
          Relevant Courses: Deep Learning, Biostatistics and Statistics, Causal Inference, Machine Learning, Digital Image Processing, Parallel Computing, Introduction and Advanced course on AR/VR.

      - layout: left
        title: Fanshawe College
        caption: August 2020 - August 2021
        sub_title: Master's, Project Management
        description: |
          Relevant Courses: Project Management, Software Lifecycle, Agile, Kanban, various other project workflows, Cost Management, Advanced Communication.

      - layout: left
        title: Western University
        caption: August 2019 - August 2020
        sub_title: Master's, Computer Engineering
        description: |
          Relevant Courses: Machine Learning, Advanced Digital Signal Processing, Audio and Speech Processing, Embedded Systems and Embedded Linux, IoT.

      - layout: left
        title: SRM Institute of Science and Technology
        caption: August 2015 - May 2019
        sub_title: Bachelor's, Computer Engineering

# Experience Section
experience:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: University of Rochester
        link: ur.rochester.edu
        sub_title: Computer Vision Research Assistant
        caption: August 2022 - Present
        description: |
          Leading a project on detection of indwelling tubes and lines in chest X-rays. Published 5 works as lead author. Currently working on an Image-to-Text Automatic Radiology Report Generation project using NLP.

      - layout: left
        title: Oz Optics Ltd.
        link: ozoptics.com
        sub_title: Machine Learning Software Engineer
        caption: August 2021 - September 2022
        description: |
          Built machine learning-based calibration software. Developed software applications in C++ and Python, interfacing with various communication protocols. Led software and PC GUI design for new products.

# Projects Section
projects:
  - title: Projects & Outside Experiences
    layout: list
    content:
      - layout: top-middle
        title: Detecting landmarks in anatomical medical images
        link: ur.rochester.edu
        description: |
          Research project conducted in collaboration with University of Rochester - Imaging Sciences Department and Carestream Health. Developed a Transformer based network for accurately detecting 6 landmark points in a chest X-ray.

      - layout: top-middle
        title: BrainScale VR
        link: ur.rochester.edu
        description: |
          NSF/NRT ARVR Graduate Student Trainee project. Developed a Virtual Reality Interactive room research lab for 3D visualization of Brain MR scans.

# Skills Section
skills:
  - title: Skills
    layout: list
    content:
      - layout: left
        title: Technical Skills
        description: |
          Deep Learning, Computer Vision, Signal Processing, NLP, C#, CUDA, Data Analysis, Flask, Git, C/C++, NumPy, Pytorch, Python, MATLAB, UI/UX Design, Unity, Software Testing, Product Management, OpenCV, SQL, MySQL, R, Power BI

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
